### PR TITLE
Bugfix/devsu 2477 filter gkb matches

### PR DESCRIPTION
**Pull request by mathieulemieux**
See https://www.bcgsc.ca/jira/browse/DEVSU-2477

### CODE REVIEW

**Comment by mathieulemieux** [comment]
Here are some before/after filtering counts:
```
/projects/POG/POG_data_hg38_no_alt/POG1858/gsc_report/gsc_report-13.0.0/genomic/F145899_F145808_F145970/ipr_report.json
before: 144
after: 115
/projects/POG/POG_data_hg38_no_alt/POG1868/gsc_report/gsc_report-13.0.0/genomic/F146248_F145962_F146348/ipr_report.json
before: 597
after: 569
/projects/POG/POG_data_hg38_no_alt/POG1911/gsc_report/gsc_report-13.0.0/genomic/F147930_F147420_F148116/ipr_report.json
before: 222
after: 205
```

**Comment by mathieulemieux** [comment]
I'll post comparisons for wildtypes tomorrow

**Comment by mathieulemieux** [comment]
/projects/POG/POG_data_hg38_no_alt/POG1868/gsc_report/gsc_report-13.0.0/genomic/F146248_F145962_F146348/ipr_report.json

before:
- 597

after:
- if wildtype are taken into account: 569
- if we do not take them into account when filtering: 577

2 unique statements affected:
- https://graphkb.bcgsc.ca/view/Statement/156:13594
- https://graphkb.bcgsc.ca/view/Statement/154:13687

**Comment by mathieulemieux** [comment]
When pori_python & ipr_api dev get fixed, I'll be able to generate comparative genomic reports.

**Review by elewis2 — APPROVED** [review]

**Pull request merged**
